#!/bin/sh
### BEGIN INIT INFO
# Provides:          wifi_access_point
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Wifi Access Point
# Description:       Takes care of creating a hotspot for this device
### END INIT INFO

HOSTSPOT_IF=wlan1

[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions

stop_wifi_ap() {
    log_daemon_msg "Stopping wifi_access_point" "wifi_access_point"

    ### stop services dhcpd and hostapd
    service isc-dhcp-server stop
    #service bind9 stop
    service hostapd stop

    ### Removing hostapd config file
    rm /etc/hostapd/hostapd.conf
    rm /etc/bind/zones/local.db
    rm /etc/bind/zones/rev.0.10.10.in-addr.arpa

    ### disable IP forwarding
    #echo 0 > /proc/sys/net/ipv4/ip_forward
    #iptables -t nat -D POSTROUTING -s 10.10.0.0/16 -o $ext_interface -j MASQUERADE 2>/dev/null

    ip link set dev $HOSTSPOT_IF down
    ip address del 10.10.0.1/24 dev $HOSTSPOT_IF
}

start_wifi_ap() {
    log_daemon_msg "Starting wifi_access_point" "wifi_access_point"

    ### give a static IP to the wifi interface
    ip link set dev $HOSTSPOT_IF up
    ip address add 10.10.0.1/24 dev $HOSTSPOT_IF

    ### enable IP forwarding
    #echo 1 > /proc/sys/net/ipv4/ip_forward
    #iptables -t nat -A POSTROUTING -s 10.10.0.0/16 -o $ext_interface -j MASQUERADE

    ##Creating hostapd conf file
    local HOSTNAME=`hostname`
    contents=$(sed -e "s|\${NETWORK_NAME}|${HOSTNAME}|g" -e "s|\${HOTSPOT_IF}|${HOSTSPOT_IF}|g" < /etc/hostapd/hostapd.conf.template)
    echo "$contents" > /etc/hostapd/hostapd.conf

    contents=$(sed -e "s|\${NETWORK_NAME}|${HOSTNAME}|g" < /etc/bind/zones/local.db.template)
    echo "$contents" > /etc/bind/zones/local.db

    contents=$(sed -e "s|\${NETWORK_NAME}|${HOSTNAME}|g" < /etc/bind/zones/rev.0.10.10.in-addr.arpa.template)
    echo "$contents" > /etc/bind/zones/rev.0.10.10.in-addr.arpa

    ### start services dhcpd and hostapd
    service hostapd start
    #service bind9 start
    service isc-dhcp-server start
}

### start/stop wifi access point
case "$1" in
    start) start_wifi_ap ;;
    stop)  stop_wifi_ap  ;;
    status)
        service hostapd status
        ret=$?
        case "$ret" in
            0)
                echo "wifi_access_point is running."
            ;;
            *)
                echo "wifi_access_point not running."
            ;;
          esac
          exit $ret
          ;;
    restart)
        stop_wifi_ap
        start_wifi_ap
    ;;
esac
